area:api:
  - 'kibble/api/*'

area:ui:
  - 'ui/*'

area:docs:
  - 'docs/*'
  - '*.md'

area:dev:
  - '.github/'
  - '.pre-commit.config.yaml'
  - 'asf.yaml'
  - 'Dockerfile*'
  - 'docker*'
  - 'setup.*'
