FROM python:3.6

USER root
RUN apt-get update
RUN apt-get install -y gcc unzip

COPY ./api /kibble/api/
COPY ./setup /kibble/setup/
COPY ./ui /kibble/ui/

RUN pip install --upgrade pip
RUN pip install -r /kibble/setup/requirements.txt

WORKDIR /kibble
