name: "PR labeler"
on:
  - pull_request_target

jobs:
  triage:
    name: Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
